apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app-backend
  template:
    metadata:
      labels:
        app: chat-app-backend
    spec:
      containers:
        - name: chat-app-backend
          image: pran1936/chat-app-backend:1.0
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: backend-env-secret
                  key: PORT
            - name: MONGO_DB_URI
              valueFrom:
                secretKeyRef:
                  name: backend-env-secret
                  key: MONGO_DB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-env-secret
                  key: JWT_SECRET
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: backend-env-secret
                  key: NODE_ENV
          resources:
            limits:
              memory: "512Mi"    
              cpu: "500m"      
            requests:
              memory: "256Mi"    
              cpu: "250m"         
---
apiVersion: v1
kind: Service
metadata:
  name: chat-app-backend-service
spec:
  selector:
    app: chat-app-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
